- l10n/po/pt_BR/_guides/kafka-dev-services.adoc.po
Hi everyone!
Translation : Dev Services for AMQP
Please check if everything is okay.
This pull request Fixes #5
> Translation : kafka-dev-services.adoc.po

- l10n/po/pt_BR/_guides/redis.adoc.po
Issue: https://github.com/quarkusio/pt.quarkus.io/issues/7
Translation redis.adoc
> Translation redis.adoc.po

- l10n/po/pt_BR/_guides/aws-lambda-snapstart.adoc.po
Hi everyone!
Translation : Dev Services for AMQP
Please check if everything is okay.
This pull request Fixes #9
> Translation : aws-lambda-snapstart.adoc.po

- l10n/po/pt_BR/_guides/cache-redis-reference.adoc.po
Hey guys,
Translation for the file cache-redis-reference.adoc.po, let me know if there's something wrong. 
Issue : https://github.com/quarkusio/pt.quarkus.io/issues/12
> translation for cache-redis-reference.adoc.po file.

- l10n/po/pt_BR/_guides/security-identity-providers.adoc.po
Hi everyone!
Translation : security-identity-providers.adoc.po
Please check if everything is okay.
fixed #18
> Translation : security-identity-providers.adoc.po

- l10n/po/pt_BR/_guides/security-basic-authentication-howto.adoc.po
Hello everyone, I kindly request a review.
fixed #16
> traducao: security-basic-authentication-howto.adoc.po

- l10n/po/pt_BR/_guides/security-oidc-configuration-properties-reference.adoc.po
Here is the Portuguese translation for the security-oidc-configuration-properties-reference.adoc.po
FIXED: #31
> Translation: security-oidc-configuration-properties-reference.adoc.po

- l10n/po/pt_BR/_guides/redis.adoc.po
Here is the Portuguese translation for the redis.adoc.po file.
I translated the '_Increment_' code as well
That PR is related to the issue fixed: #22 
PS: This is my very first open source contribution so feel free to correct me if I did something wrong.
> Translation: redis.adoc.po

- l10n/po/pt_BR/_guides/camel.adoc.po
Here is the Portuguese translation for the redis.adoc.po file.
FIXED: #29
> Translation: camel.adoc.po

- l10n/po/pt_BR/_guides/funqy-gcp-functions-http.adoc.po
Here is the Portuguese translation for the funqy-gcp-functions-http.adoc.po
FIXED: #34
> Translation: funqy-gcp-functions-http.adoc.po

- l10n/po/pt_BR/_guides/virtual-threads.adoc.po
> virtual threads translation

- l10n/po/pt_BR/_guides/kubernetes-dev-services.adoc.po
Here is the Portuguese translation for the kubernetes-dev-services.adoc.po
FIXED: #46
> Translation: kubernetes-dev-services.adoc.po

- l10n/po/pt_BR/_guides/pulsar-dev-services.adoc.po
Here is the Portuguese translation for the pulsar-dev-services.adoc.po
FIXED: #48
> Translation: pulsar-dev-services.adoc.po

- l10n/po/pt_BR/_guides/tooling.adoc.po
Here is the Portuguese translation for the tooling.adoc.po
FIXED: #51
> Translation: tooling.adoc.po

- l10n/po/pt_BR/newsletter.md.po
Translate to Portuguese(Pt-Br) from the newsletter archive
FIXED: #54
> traducao: newsletter.md.po

- l10n/po/pt_BR/_guides/building-native-image.adoc.po
Translation of the guide building-native-image
FIXED: #55
> traducao: building-native-image

- .github/steps/create-issue-if-override-files-updated
Copied from https://github.com/quarkusio/ja.quarkus.io/blob/main/.github/steps/create-issue-if-override-files-updated
> Update `create-issue-if-override-files-updated` script

- l10n/po/pt_BR/_guides/grpc.adoc.po
translate: grpc.adoc.po
FIXED: #66
> translate: grpc.adoc.po

- l10n/po/pt_BR/_guides/doc-concept.adoc.po
> Translate doc-concept.adoc

- l10n/po/pt_BR/_guides/grpc-service-consumption.adoc.po
translate: grpc-service-consumption.adoc.po
FIXED: #71
> traducao: grpc-service-consumption.adoc.po

- l10n/po/pt_BR/_guides/aws-lambda.adoc.po
> Translate: aws-lambda.adoc.po

- config/l10n-utils.json
This update fixes the bug that fuzzy.tmx is not applied.
> Update doc-l10n-kit to 0.9.5.RELEASE

- .github/workflows/build.yml
- .github/workflows/create-glossary.yml
- .github/workflows/delete-glossary.yml
- .github/workflows/list-glossaries.yml
- .github/workflows/pull-request.yml
- .github/workflows/sync.yml
To address the build failure: https://github.com/quarkusio/pt.quarkus.io/actions/runs/7223202871
> Update GitHub Actions container

- l10n/po/pt_BR/_guides/quarkus-maven-plugin.adoc.po
- l10n/po/pt_BR/_versions/main/guides/quarkus-maven-plugin.adoc.po
> Tradução quarkus-maven-plugin.adoc.po

- l10n/po/pt_BR/_guides/cdi-integration.adoc.po
> Translate cdi integration

- l10n/po/pt_BR/_guides/getting-started-reactive.adoc.po
> Traduzir getting-started-reactive.adoc.po

- l10n/po/pt_BR/_guides/rest-client-reactive.adoc.po
> Traduzir rest-client-reactive.adoc.po

- l10n/po/pt_BR/_guides/redis.adoc.po
> Traduzir redis.adoc.po

- l10n/po/pt_BR/_guides/_includes/devtools/build-native-container-parameters.adoc.po
- l10n/po/pt_BR/_guides/_includes/devtools/build-native-container.adoc.po
- l10n/po/pt_BR/_guides/_includes/devtools/build-native.adoc.po
- l10n/po/pt_BR/_guides/_includes/devtools/build.adoc.po
- l10n/po/pt_BR/_guides/_includes/devtools/create-app.adoc.po
- l10n/po/pt_BR/_guides/_includes/devtools/create-cli.adoc.po
- l10n/po/pt_BR/_guides/_includes/devtools/dev-parameters.adoc.po
- l10n/po/pt_BR/_guides/_includes/devtools/dev.adoc.po
- l10n/po/pt_BR/_guides/_includes/devtools/extension-add.adoc.po
- l10n/po/pt_BR/_guides/_includes/devtools/maven-opts.adoc.po
- l10n/po/pt_BR/_guides/_includes/devtools/test.adoc.po
> Traduzir diretório guides/includes/devtools

- l10n/po/pt_BR/_guides/building-native-image.adoc.po
> Traduzir building-native-image.adoc.po

- l10n/po/pt_BR/_guides/dev-services.adoc.po
> Traduzir dev-services.adoc.po

- l10n/po/pt_BR/_guides/all-builditems.adoc.po
- l10n/po/pt_BR/_guides/cache-redis-reference.adoc.po
> Translate all-builditems.adoc.po e cache-redis-reference.adoc.po

- l10n/po/pt_BR/_guides/podman.adoc.po
> Translate podman.adoc.po

- l10n/po/pt_BR/_guides/security-getting-started-tutorial.adoc.po
> Translate security-getting-started-tutorial.adoc.po

- l10n/po/pt_BR/_guides/redis-dev-services.adoc.po
> Translate redis-dev-services.adoc.po

- l10n/po/pt_BR/_guides/kubernetes-dev-services.adoc.po
> Translate kubernetes-dev-services.adoc.po

- l10n/po/pt_BR/_guides/grpc-virtual-threads.adoc.po
- l10n/po/pt_BR/_guides/security-cors.adoc.po
> Translate grpc-virtual-threads.adoc.po and security-cors.adoc.po

- l10n/po/pt_BR/_guides/kafka.adoc.po
Fixes #151 
@gastaldi, i noticed that Openshift links are mostly broken. I left the fuzzy marks in the messages containing these links. I believe that some of them are from subdomains not accessbile without an account. But there are others which don't seem like so.
> Translate kafka.adoc.po

- l10n/po/pt_BR/_guides/config-mappings.adoc.po
> Translate config-mappings.adoc.po

- l10n/po/pt_BR/_guides/security-overview.adoc.po
Translate from EN to PT guide > Security overview
> Translate from EN to PT guide > Security overview

- l10n/po/pt_BR/_guides/security-basic-authentication.adoc.po
> Tradução: `security-basic-authentication.adoc.po`

- l10n/po/pt_BR/_guides/security-basic-authentication-howto.adoc.po
> Translate `security-basic-authentication-howto.adoc.po`

- l10n/po/pt_BR/_guides/flyway.adoc.po
> Translate: `flyway.adoc.po`

- l10n/po/pt_BR/_guides/security-vulnerability-detection.adoc.po
Hey guys (Gastaldi and Luis),
I restarted the process. So I created a new branch 'vulnerability' and sent you just the translation about 'vulnerability'. After that, I'll create a new branch about 'security' and send the other adjusts related "msgtr", Ok?
Thanks!
> Translate guide > vulnerability from EN to PT-BR

- l10n/po/pt_BR/_guides/security-overview.adoc.po
Hey guys (Gastaldi and Luis),
Now, follow the other "new branch" about the 'security' guide that fixes "msgtr" token.
Thanks! :)
> Fixes "msgtr" token related to the 'security' guide

- l10n/po/pt_BR/_guides/podman.adoc.po
Tradução da pagina using podman with Quarkus.
- FIXES: #198
> traducao: podman.adoc.po

- l10n/po/pt_BR/_guides/websockets.adoc.po
> traducao: Websockets.adoc.po

- l10n/po/pt_BR/_guides/funqy-aws-lambda-http.adoc.po
- l10n/po/pt_BR/_guides/funqy-azure-functions-http.adoc.po
> Traducao: funqy-aws-lambda-http.adoc.po

- l10n/po/pt_BR/_guides/security-overview.adoc.po
Olá, terminei a revisão do 'security-overview.adoc.po' e agora o commit está correto! :D
Qualquer dúvida estou à disposição, abraços
> Tradução 'security-overview.adoc.po'

- l10n/po/pt_BR/_versions/main/guides/drools.adoc.po
> traducao: drools.po
